language:
  - node_js

node_js:
  - 10.6

install:
  - npm install -g grunt
  - npm install -g sass
  - npm install

script:
  - grunt

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds